language: go
go:
  - 1.6
sudo: false
before_install:
  - openssl aes-256-cbc -K $encrypted_75579ba057cb_key -iv $encrypted_75579ba057cb_iv -in .netrc.enc -out .netrc -d
  - chmod 600 .netrc
  - cp .netrc ~
install:
  - wget -q -O - https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-linux-amd64.tar.gz | tar xvz
  - linux-amd64/glide install
  - wget -q https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.48.zip -O go_appengine_sdk.zip
  - unzip -q go_appengine_sdk.zip
  - export PATH=$PATH:$PWD/go_appengine
script:
  - make test
