[metadata]
  project = "momoclo-channel"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/line/line-bot-sdk-go"

[[constraint]]
  branch = "master"
  name = "github.com/mjibson/goon"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.2.0"

[[constraint]]
  name = "github.com/utahta/go-linenotify"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/utahta/go-openuri"

[[constraint]]
  name = "github.com/utahta/go-twitter"
  version = "0.2.0"

[[constraint]]
  name = "github.com/utahta/momoclo-crawler"
  revision = "c771f7aaf36dba558172b2d5c225b1e0a324efb1"

[[constraint]]
  branch = "master"
  name = "github.com/utahta/ustream-live-status"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "google.golang.org/api"
  branch = "master"

[[constraint]]
  name = "google.golang.org/appengine"
  branch = "master"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/cenkalti/backoff"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "^3.2.1"

[[constraint]]
  name = "github.com/go-playground/validator"
  version = "^9.9.0"
