version: v1-0-0
runtime: go
api_version: go1

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  max_concurrent_requests: 80
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /images
  static_dir: public/images
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /cron/crawl
  script: _go_app
  login: admin

- url: /cron/ustream
  script: _go_app
  login: admin

- url: /cron/reminder
  script: _go_app
  login: admin

- url: /linebot/callback
  script: _go_app
- url: /linebot/help
  script: _go_app
- url: /linebot/about
  script: _go_app

- url: /linenotify/on
  script: _go_app
- url: /linenotify/off
  script: _go_app
- url: /linenotify/callback
  script: _go_app

- url: /.*
  script: _go_app
  login: admin
