version: v3-0-0
runtime: go
api_version: go1.8

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  max_concurrent_requests: 50
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /images
  static_dir: public/images
- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /line/bot/callback
  script: _go_app
- url: /line/bot/help
  script: _go_app
- url: /line/bot/about
  script: _go_app

- url: /line/notify/on
  script: _go_app
- url: /line/notify/off
  script: _go_app
- url: /line/notify/callback
  script: _go_app

- url: /.*
  script: _go_app
  login: admin
