service: queue
version: v1-0-0
runtime: go
api_version: go1

instance_class: B2
basic_scaling:
  idle_timeout: 1m
  max_instances: 1

handlers:
- url: /_ah/start
  script: _go_app
  login: admin

- url: /queue/tweet
  script: _go_app
  login: admin

- url: /queue/line
  script: _go_app
  login: admin
