service: queue
version: v1-0-0
runtime: go
api_version: go1

instance_class: F2
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 80
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
- url: /queue/tweet
  script: _go_app
  login: admin

- url: /queue/line
  script: _go_app
  login: admin
