baseurl = "https://utahta.github.io/momoclo-channel/"
languageCode = "en-us"
title = "momoclo-channel"
copyright = "&copy; <a href=\"https://github.com/utahta\">utahta</a> 2016"
theme = "slim"

[params]
  GithubID = "utahta"
  TwitterID = "utahta"
  Summary = false
  Content = true
