baseurl = "https://utahta.github.io/momoclo-channel/"
languageCode = "en-us"
title = "momoclo-channel"

[params]
    author = "utahta"

    version = ""
    logo = ""
    favicon = ""

    permalink = "#"

    custom_css = []
    custom_js  = []

    highlight_css  = ""

    [params.palette]
        primary = "red"
        accent  = "light-green"

    [social]
        twitter = "utahta"
        github  = "utahta"

[[menu.main]]
	name   = ""
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "LINE BOT"
	url    = "linebot/"
	weight = 10
